on: workflow_dispatch
name: Manual Lister Dashium Modules
jobs:
  render:
    name: Manual Lister Dashium Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Chmod
        run: chmod +x ./script/release.sh
      - run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}